Add explicit HTTP method for InternalController.GetStyles
Fix swagger endpoint

Swashbuckle.AspNetCore.SwaggerGen.SwaggerGeneratorException: Ambiguous HTTP method for action - Jellyfin.Plugin.ListenBrainz.Controllers.InternalController.GetStyles (Jellyfin.Plugin.ListenBrainz). Actions require
 an explicit HttpMethod binding for Swagger/OpenAPI 3.0